### ISSUE TITLE
The document of todo tutorial with Thymeleaf seems same as the one with JSP.

### ISSUE THREAD

**Issue by neriudon** [Macchinetta/server-guideline-thymeleaf#1]
## Description
日本語で失礼します。
この度、MacchinettaのガイドラインをベースにThymeleafを学習しようと思い[11.1. チュートリアル(Todoアプリケーション)](https://macchinetta.github.io/server-guideline-thymeleaf/current/ja/Tutorial/TutorialTodo.html)に従って`archetypeArtifactId=macchinetta-web-blank-noorm-thymeleaf-archetype`を指定して作成したブランクプロジェクトを使って演習を行っていました。
すると、[11.1.3.5. プロジェクトの動作確認](https://macchinetta.github.io/server-guideline-thymeleaf/current/ja/Tutorial/TutorialTodo.html#id16)で「ブランクプロジェクトから提供されている**JSP**」と記述があり、その下に`Thymeleaf`版のブランクプロジェクトには生成されない`JSP`のコード例が表示されていることに気づきました。
さらに読み進めると[11.1.4.2.2.3. JSPの作成](https://macchinetta.github.io/server-guideline-thymeleaf/current/ja/Tutorial/TutorialTodo.html#jsp)という節があり、`list.jsp`を作成するよう書かれていますが、記事通りに作成して実行すると、`todo/list.html`がないというエラーになります。
```
Caused by: java.io.FileNotFoundException: Could not open ServletContext resource [/WEB-INF/views/todo/list.html]
	at org.springframework.web.context.support.ServletContextResource.getInputStream(ServletContextResource.java:141)
	at org.thymeleaf.spring4.templateresource.SpringResourceTemplateResource.reader(SpringResourceTemplateResource.java:103)
	at org.thymeleaf.templateparser.markup.AbstractMarkupTemplateParser.parse(AbstractMarkupTemplateParser.java:223)
	... 101 more
```
ためしに[JSP版のTodoチュートリアル](https://github.com/Macchinetta/server-guideline/blob/master/source/Tutorial/TutorialTodo.rst)のページと、[Thymeleaf版のTodoチュートリアル](https://github.com/Macchinetta/server-guideline-thymeleaf/blob/master/source/Tutorial/TutorialTodo.rst)のページの`diff`を取ったところ、以下のようにブランクプロジェクトを生成するコマンドしか差分がないことがわかりました。
```
213c213
<     Bash上で\ ``mvn archetype:generate``\ を実行する場合は、以下のように"\ ``^``\" を\ ``\``\ に置き換えて実行すればよい。
---
>     Bash上で\ ``mvn archetype:generate``\ を実行する場合は、以下のように"\ ``^``\" を"\ ``\``\" に置き換えて実行すればよい。
219c219
<          -DarchetypeArtifactId=macchinetta-web-blank-noorm-thymeleaf-archetype\
---
>          -DarchetypeArtifactId=macchinetta-web-blank-noorm-archetype\
239c239
<      -DarchetypeArtifactId=macchinetta-web-blank-noorm-thymeleaf-archetype^
---
>      -DarchetypeArtifactId=macchinetta-web-blank-noorm-archetype^
257c257
<      -DarchetypeArtifactId=macchinetta-web-blank-thymeleaf-archetype^
---
>      -DarchetypeArtifactId=macchinetta-web-blank-archetype^
```
これはThymeleaf版の誤植ではないでしょうか？

## Possible Solutions
(Please write ideas or candidates of solutions for the problem if you have)

## Affects Version/s
- 1.X.X.RELEASE

## Fix Version/s
(To be written later by project member)

## Issue Links
- #XXX

**Comment by macchinetta-fw** [comment]
Thymeleaf版のガイドラインはJSP版をベースに作成しておりますが、Thymeleaf化するにあたり特に重要となる節を優先的に作成したため、"11. チュートリアル"を含む一部の節の記述はJSP版のままとなっています。

次版(1.6.0.RELEASE)以降で残りの節も全てThymeleaf化する予定なので少々お待ち下さい。 

なお、1.5.x.RELEASEでThymeleaf化されていない節の一覧を[Wiki](https://github.com/Macchinetta/server-guideline-thymeleaf/wiki/1.5.x.RELEASE)にまとめ、[GitHub PagesのWebページ](https://macchinetta.github.io/server.html)から「ご利用上の注意」という形でリンクを追加するようにしました(e435bdb8212a76c58b809344714a0601f731b720)。1.5.x.RELEASEを利用される場合はこちらもご参照ください。

**Comment by neriudon** [comment]
@macchinetta-fw 
ご返答ありがとうございます。
また、Wikiへの記載やトップページでの注意喚起対応をしていただきありがとうございます。
一部の節の記述がJSP版のままになっている件は把握いたしましたので、特に問題がなければ本イシューをクローズしていただけないでしょうか？宜しくお願い致します。

それではThymeleaf化されるのをお待ちしております。
